spring:
  main:
    banner-mode: off
  profiles:
    active: dev
    include: lifecycle


root-log-level: INFO
default-log-level: INFO
# 单个log文件大小
log-file-size: "2048 MB"
# 每天每个appender产生的日志文件个数上限
log-file-count: 10
# 历史日志最多保留的时间
log-file-duration: 14d

server:
  port: 4567